const findQAs = (v1) => {
    const ans = {
        personalQA: [{}],
        socialQA: [{}],
        academicQA: [{}],
        occupationalQA: [{}],
        recreationalQA: [{}],
    }
    if (v1 == "preprimary") {
        ans.personalQA = [{ question: "Chews and swallows solid food when placed in his mouth", answer: "" },
        { question: "Holds and drinks water or milk or juice from a glass or cup", answer: "" },
        { question: "Eats by self with fingers when food is mixed and given", answer: "" },
        { question: "Sits on potty or squats to pass urine or stools", answer: "" },
        { question: "Indicates verbally or through gestures the need to go to the toilet", answer: "" },
        { question: "Takes off under clothes to use toilet (when unbuttoned/ pulling clastic pants)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder", answer: "" },
        { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
        { question: "Takes off clothes (inlcuding under garments) when unbuttoned", answer: "" },
        { question: "Wears undergarments", answer: "" },
        { question: "Cleans nose with a handkerchief", answer: "" },
        { question: "Washes hands before eating snacks or food or after using toilet or when hands are dirty", answer: "" },
        { question: "Wipes with a towel after bath", answer: "" },
        { question: "Peels off fruits such as orange and banana before eating", answer: "" },
        { question: "Eats with an appropriate side dish such as bread & jam, chapati & curry, Idli & chutncy", answer: "" },
        { question: "Mixes and eats by self without spilling", answer: "" },
        { question: "Wipes hand and mouth with a towel after washing", answer: "" },
        { question: "Wears slippers", answer: "" },
        { question: "Wears shoes without shoe lace or buckle", answer: "" }]
        ans.socialQA = [{ question: "Moves head or eyes to see persons moving near him or in the room", answer: "" },
        { question: "Responds to his name by stopping an activity or looking at the person when called", answer: "" },
        { question: "Goes to a familiar person when asked to come near him", answer: "" },
        { question: "Smiles when other person smiles at him", answer: "" },
        { question: "Plays with two other children cooperatively", answer: "" },
        { question: "Waits for his turn in the classroom, play ground, dining room", answer: "" },
        { question: "Shares his things (pencil, books, eraser, toys and eatables) when requested by his classmates or others", answer: "" },
        { question: "Greets teachers or elders in school or at home", answer: "" },
        { question: "Differentiates strangers from familiar people", answer: "" },
        { question: "Expresses anger displeasure by vocalizations (shouting/turning away/ screaming) other than crying", answer: "" },
        { question: "Stops momentarily an activity when said 'no'", answer: "" },
        { question: "Uses vocal sounds/gestures/actions to call a person/to get attention of others", answer: "" },
        { question: "Responds appropriately to words alongwith gestures such as come, up, go, bye-bye, etc", answer: "" },
        { question: "Uses gestures such as shaking head for 'no', head nodding for 'yes' hand gesture for 'come', 'give', 'sleep', 'tata'", answer: "" },
        { question: "Follows simple verbal requests with gestures such as 'give', 'I will take' (response could be gestural or verbal)", answer: "" },
        { question: "Uses words such as 'mama', 'nana', 'deedi', 'bow bow', etc", answer: "" },
        { question: "Follows simple commands without gestures like 'where is the ball', 'put that down', 'bring the ball", answer: "" },
        { question: "Answers questions such as 'how does a car go', 'how does an aeroplane go', 'how do you apply face powder', (responses inmiming fashion)", answer: "" },
        { question: "Identifies persons by pointing or naming upon request (eg, uncle, aunty, sister, brother, etc.)", answer: "" },
        { question: "Asks for desired objects using gestures/alongwith vocalizations", answer: "" },
        { question: "Tells him name when asked", answer: "" },
        { question: "Gestures/says suitably for Namaste/salam/good morning", answer: "" }]
        ans.academicQA = [
            { question: "Points/shows body parts (head, nose, cycs, cars, hands, legs) when requested.", answer: "" },
            { question: "Names body parts when pointed to", answer: "" },
            { question: "Paints to 10 comman objects with which he has to interact in his/her home environment (eg.rice, dall, chapati, light, fan, mat, table, chair, shirt/frock, shorts/pants,etc.), when asked or when he wants", answer: "" },
            { question: "Says orally the names of the 10 common objects when shown when he wants.", answer: "" },
            { question: "Holds pencil and scribbles", answer: "" },
            { question: "Colours with a crayon within a given diagram", answer: "" },
            { question: "Traces on the given diagram", answer: "" },
            { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
            { question: "Copics a given figure/diagram", answer: "" },
            { question: "Groups common colours (red, green, blur, yellow) when given a group of coloured objects", answer: "" },
            { question: "Groups objects according to the size (big and small, long and short)", answer: "" },
            { question: "Gives objects/pictures of common colours when asked", answer: "" },
            { question: "Names common colours. (red, green, blue, yellow)", answer: "" },
            { question: "Points to the objects which are big and small/long and short upon request", answer: "" },
            { question: "Tells the size of the ohjeets (big & small, long & short)", answer: "" },
            { question: "Points to sets of objects to show more/less quantity", answer: "" },
            { question: "Tells which set has moreless quantity", answer: "" },
            { question: "Points to containers with either solids/liquids to show full and empty", answer: "" },
            { question: "Fells when a container is shown cither full or empty with or without liquid or solid", answer: "" },
            { question: "Rete counis upto 5", answer: "" },
            { question: "Counts and gives objects upto 5 when not asked sequentially", answer: "" },
            { question: "Counts and gives objects upto 10 when not asked sequentially.", answer: "" },
            { question: "Shows a numeral and places value when not asked sequentially", answer: "" },
            { question: "Names upto 5 numbers when not asked sequentially", answer: "" },
            { question: "Writes numerals upto 5 in a sequence", answer: "" },
            { question: "Writes numerals upto 5 when given dictation not sequentially", answer: "" },
            { question: "Points to alphabets (English/regional language) on a chart not asked sequentially (3 letter words in case of sight word icaching)", answer: "" },
            { question: "Names alphabets when asked not sequentially (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Writes alphabets when given dictation (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Identifies a clock or wrist watch", answer: "" },
            { question: "Tells points to when asked the use of clock or wrist watch", answer: "" },
            { question: "Differentiates money from other objects", answer: "" },
            { question: "Tells points to when asked the use of money", answer: "" },
            { question: "Groups Rs. 1, 2, 5 notes when given", answer: "" },
            { question: "Grck 1, 2, 5 rupee notes when asked", answer: "" },
            { question: "Points/tells when asked by showing Rs.1, 2, 5 notes", answer: "" },
            { question: "Counts and gives 1 rupee notes upto Rs.5 when asked", answer: "" },
            { question: "Points to atleast 5 pictures of animals when asked)", answer: "" },
            { question: "Names atleast 5 animals when shown pictures", answer: "" },
            { question: "Points to atleast 5 pictures of fruits when asked", answer: "" },
            { question: "Names atleast 5 fruits when shown pictures", answer: "" },
            { question: "Tells/points to the clothes (frock, shorts, shirt, T-shirt)he/she wears when asked", answer: "" },
            { question: "Uses words or gestures for 'now and later when necessary", answer: "" },
            { question: "Identifies/Names the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, acroplane, train)", answer: "" },]
        ans.occupationalQA = [
            { question: "Dusts with a duster the furniture in the classroom and home", answer: "" },
            { question: "Washes glasses and plates before and after meals.", answer: "" },
            { question: "Wipes glasses and plates with a cloth after washing", answer: "" },
            { question: "Folds small clothes (such as hand towel/panties).", answer: "" }]
        ans.recreationalQA = [{ question: "Watches T.V.Advertisements(indoor)", answer: "" },
        { question: "Dances/claps/taps with rhythm of music in Radio or T.V. (indoor)", answer: "" },
        { question: "Plays with block assembling and dismantling (indoor)", answer: "" },
        { question: "Colours with pencils or crayons (indoor)", answer: "" },
        { question: "Plays make believe games pretending to be teacher, mummy, daddy or elder sibling going to school/household keeping (indoor)", answer: "" },
        { question: "Arranges own things in their appropriate places, in a given room (indoor)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder (indoor)", answer: "" },
        { question: "Sees pictures in magazines without tearing the book (indoor)", answer: "" },//Sees pictures in magazines without tearing the book
        { question: "Plays with ball", answer: "" },
        { question: "Plays running and catching game/runs a race/duck walking/frog jumping, etc", answer: "" },
        { question: "Climbs jungle gym etc", answer: "" },
        { question: "Sand play", answer: "" },
        { question: "Water play", answer: "" },
        { question: "Plays hide and seek game/passing the parcel/musical chairs, etc", answer: "" },
        { question: "Plays on a slide", answer: "" },
        { question: "Swings on a swing", answer: "" }]
    }
    else if (v1 == "primary1") {
        ans.personalQA = [{ question: "Chews and swallows solid food when placed in his mouth", answer: "" },
        { question: "Holds and drinks water or milk or juice from a glass or cup", answer: "" },
        { question: "Eats by self with fingers when food is mixed and given", answer: "" },
        { question: "Sits on potty or squats to pass urine or stools", answer: "" },
        { question: "Indicates verbally or through gestures the need to go to the toilet", answer: "" },
        { question: "Takes off under clothes to use toilet (when unbuttoned/ pulling clastic pants)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder", answer: "" },
        { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
        { question: "Takes off clothes (inlcuding under garments) when unbuttoned", answer: "" },
        { question: "Wears undergarments", answer: "" },
        { question: "Cleans nose with a handkerchief", answer: "" },
        { question: "Washes hands before eating snacks or food or after using toilet or when hands are dirty", answer: "" },
        { question: "Wipes with a towel after bath", answer: "" },
        { question: "Peels off fruits such as orange and banana before eating", answer: "" },
        { question: "Eats with an appropriate side dish such as bread & jam, chapati & curry, Idli & chutncy", answer: "" },
        { question: "Mixes and eats by self without spilling", answer: "" },
        { question: "Wipes hand and mouth with a towel after washing", answer: "" },
        { question: "Wears slippers", answer: "" },
        { question: "Wears shoes without shoe lace or buckle", answer: "" }]
        ans.socialQA = [{ question: "Moves head or eyes to see persons moving near him or in the room", answer: "" },
        { question: "Responds to his name by stopping an activity or looking at the person when called", answer: "" },
        { question: "Goes to a familiar person when asked to come near him", answer: "" },
        { question: "Smiles when other person smiles at him", answer: "" },
        { question: "Plays with two other children cooperatively", answer: "" },
        { question: "Waits for his turn in the classroom, play ground, dining room", answer: "" },
        { question: "Shares his things (pencil, books, eraser, toys and eatables) when requested by his classmates or others", answer: "" },
        { question: "Greets teachers or elders in school or at home", answer: "" },
        { question: "Differentiates strangers from familiar people", answer: "" },
        { question: "Expresses anger displeasure by vocalizations (shouting/turning away/ screaming) other than crying", answer: "" },
        { question: "Stops momentarily an activity when said 'no'", answer: "" },
        { question: "Uses vocal sounds/gestures/actions to call a person/to get attention of others", answer: "" },
        { question: "Responds appropriately to words alongwith gestures such as come, up, go, bye-bye, etc", answer: "" },
        { question: "Uses gestures such as shaking head for 'no', head nodding for 'yes' hand gesture for 'come', 'give', 'sleep', 'tata'", answer: "" },
        { question: "Follows simple verbal requests with gestures such as 'give', 'I will take' (response could be gestural or verbal)", answer: "" },
        { question: "Uses words such as 'mama', 'nana', 'deedi', 'bow bow', etc", answer: "" },
        { question: "Follows simple commands without gestures like 'where is the ball', 'put that down', 'bring the ball", answer: "" },
        { question: "Answers questions such as 'how does a car go', 'how does an aeroplane go', 'how do you apply face powder', (responses inmiming fashion)", answer: "" },
        { question: "Identifies persons by pointing or naming upon request (eg, uncle, aunty, sister, brother, etc.)", answer: "" },
        { question: "Asks for desired objects using gestures/alongwith vocalizations", answer: "" },
        { question: "Tells him name when asked", answer: "" },
        { question: "Gestures/says suitably for Namaste/salam/good morning", answer: "" }]
        ans.academicQA = [
            { question: "Points/shows body parts (head, nose, cycs, cars, hands, legs) when requested.", answer: "" },
            { question: "Names body parts when pointed to", answer: "" },
            { question: "Paints to 10 comman objects with which he has to interact in his/her home environment (eg.rice, dall, chapati, light, fan, mat, table, chair, shirt/frock, shorts/pants,etc.), when asked or when he wants", answer: "" },
            { question: "Says orally the names of the 10 common objects when shown when he wants.", answer: "" },
            { question: "Holds pencil and scribbles", answer: "" },
            { question: "Colours with a crayon within a given diagram", answer: "" },
            { question: "Traces on the given diagram", answer: "" },
            { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
            { question: "Copics a given figure/diagram", answer: "" },
            { question: "Groups common colours (red, green, blur, yellow) when given a group of coloured objects", answer: "" },
            { question: "Groups objects according to the size (big and small, long and short)", answer: "" },
            { question: "Gives objects/pictures of common colours when asked", answer: "" },
            { question: "Names common colours. (red, green, blue, yellow)", answer: "" },
            { question: "Points to the objects which are big and small/long and short upon request", answer: "" },
            { question: "Tells the size of the ohjeets (big & small, long & short)", answer: "" },
            { question: "Points to sets of objects to show more/less quantity", answer: "" },
            { question: "Tells which set has moreless quantity", answer: "" },
            { question: "Points to containers with either solids/liquids to show full and empty", answer: "" },
            { question: "Fells when a container is shown cither full or empty with or without liquid or solid", answer: "" },
            { question: "Rete counis upto 5", answer: "" },
            { question: "Counts and gives objects upto 5 when not asked sequentially", answer: "" },
            { question: "Counts and gives objects upto 10 when not asked sequentially.", answer: "" },
            { question: "Shows a numeral and places value when not asked sequentially", answer: "" },
            { question: "Names upto 5 numbers when not asked sequentially", answer: "" },
            { question: "Writes numerals upto 5 in a sequence", answer: "" },
            { question: "Writes numerals upto 5 when given dictation not sequentially", answer: "" },
            { question: "Points to alphabets (English/regional language) on a chart not asked sequentially (3 letter words in case of sight word icaching)", answer: "" },
            { question: "Names alphabets when asked not sequentially (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Writes alphabets when given dictation (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Identifies a clock or wrist watch", answer: "" },
            { question: "Tells points to when asked the use of clock or wrist watch", answer: "" },
            { question: "Differentiates money from other objects", answer: "" },
            { question: "Tells points to when asked the use of money", answer: "" },
            { question: "Groups Rs. 1, 2, 5 notes when given", answer: "" },
            { question: "Grck 1, 2, 5 rupee notes when asked", answer: "" },
            { question: "Points/tells when asked by showing Rs.1, 2, 5 notes", answer: "" },
            { question: "Counts and gives 1 rupee notes upto Rs.5 when asked", answer: "" },
            { question: "Points to atleast 5 pictures of animals when asked)", answer: "" },
            { question: "Names atleast 5 animals when shown pictures", answer: "" },
            { question: "Points to atleast 5 pictures of fruits when asked", answer: "" },
            { question: "Names atleast 5 fruits when shown pictures", answer: "" },
            { question: "Tells/points to the clothes (frock, shorts, shirt, T-shirt)he/she wears when asked", answer: "" },
            { question: "Uses words or gestures for 'now and later when necessary", answer: "" },
            { question: "Identifies/Names the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, acroplane, train)", answer: "" },]
        ans.occupationalQA = [
            { question: "Dusts with a duster the furniture in the classroom and home", answer: "" },
            { question: "Washes glasses and plates before and after meals.", answer: "" },
            { question: "Wipes glasses and plates with a cloth after washing", answer: "" },
            { question: "Folds small clothes (such as hand towel/panties).", answer: "" }]
        ans.recreationalQA = [{ question: "Watches T.V.Advertisements(indoor)", answer: "" },
        { question: "Dances/claps/taps with rhythm of music in Radio or T.V. (indoor)", answer: "" },
        { question: "Plays with block assembling and dismantling (indoor)", answer: "" },
        { question: "Colours with pencils or crayons (indoor)", answer: "" },
        { question: "Plays make believe games pretending to be teacher, mummy, daddy or elder sibling going to school/household keeping (indoor)", answer: "" },
        { question: "Arranges own things in their appropriate places, in a given room (indoor)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder (indoor)", answer: "" },
        { question: "Sees pictures in magazines without tearing the book (indoor)", answer: "" },//Sees pictures in magazines without tearing the book
        { question: "Plays with ball", answer: "" },
        { question: "Plays running and catching game/runs a race/duck walking/frog jumping, etc", answer: "" },
        { question: "Climbs jungle gym etc", answer: "" },
        { question: "Sand play", answer: "" },
        { question: "Water play", answer: "" },
        { question: "Plays hide and seek game/passing the parcel/musical chairs, etc", answer: "" },
        { question: "Plays on a slide", answer: "" },
        { question: "Swings on a swing", answer: "" }]
    }
    else if (v1 == "primary2") {
        ans.personalQA = [{ question: "Chews and swallows solid food when placed in his mouth", answer: "" },
        { question: "Holds and drinks water or milk or juice from a glass or cup", answer: "" },
        { question: "Eats by self with fingers when food is mixed and given", answer: "" },
        { question: "Sits on potty or squats to pass urine or stools", answer: "" },
        { question: "Indicates verbally or through gestures the need to go to the toilet", answer: "" },
        { question: "Takes off under clothes to use toilet (when unbuttoned/ pulling clastic pants)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder", answer: "" },
        { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
        { question: "Takes off clothes (inlcuding under garments) when unbuttoned", answer: "" },
        { question: "Wears undergarments", answer: "" },
        { question: "Cleans nose with a handkerchief", answer: "" },
        { question: "Washes hands before eating snacks or food or after using toilet or when hands are dirty", answer: "" },
        { question: "Wipes with a towel after bath", answer: "" },
        { question: "Peels off fruits such as orange and banana before eating", answer: "" },
        { question: "Eats with an appropriate side dish such as bread & jam, chapati & curry, Idli & chutncy", answer: "" },
        { question: "Mixes and eats by self without spilling", answer: "" },
        { question: "Wipes hand and mouth with a towel after washing", answer: "" },
        { question: "Wears slippers", answer: "" },
        { question: "Wears shoes without shoe lace or buckle", answer: "" }]
        ans.socialQA = [{ question: "Moves head or eyes to see persons moving near him or in the room", answer: "" },
        { question: "Responds to his name by stopping an activity or looking at the person when called", answer: "" },
        { question: "Goes to a familiar person when asked to come near him", answer: "" },
        { question: "Smiles when other person smiles at him", answer: "" },
        { question: "Plays with two other children cooperatively", answer: "" },
        { question: "Waits for his turn in the classroom, play ground, dining room", answer: "" },
        { question: "Shares his things (pencil, books, eraser, toys and eatables) when requested by his classmates or others", answer: "" },
        { question: "Greets teachers or elders in school or at home", answer: "" },
        { question: "Differentiates strangers from familiar people", answer: "" },
        { question: "Expresses anger displeasure by vocalizations (shouting/turning away/ screaming) other than crying", answer: "" },
        { question: "Stops momentarily an activity when said 'no'", answer: "" },
        { question: "Uses vocal sounds/gestures/actions to call a person/to get attention of others", answer: "" },
        { question: "Responds appropriately to words alongwith gestures such as come, up, go, bye-bye, etc", answer: "" },
        { question: "Uses gestures such as shaking head for 'no', head nodding for 'yes' hand gesture for 'come', 'give', 'sleep', 'tata'", answer: "" },
        { question: "Follows simple verbal requests with gestures such as 'give', 'I will take' (response could be gestural or verbal)", answer: "" },
        { question: "Uses words such as 'mama', 'nana', 'deedi', 'bow bow', etc", answer: "" },
        { question: "Follows simple commands without gestures like 'where is the ball', 'put that down', 'bring the ball", answer: "" },
        { question: "Answers questions such as 'how does a car go', 'how does an aeroplane go', 'how do you apply face powder', (responses inmiming fashion)", answer: "" },
        { question: "Identifies persons by pointing or naming upon request (eg, uncle, aunty, sister, brother, etc.)", answer: "" },
        { question: "Asks for desired objects using gestures/alongwith vocalizations", answer: "" },
        { question: "Tells him name when asked", answer: "" },
        { question: "Gestures/says suitably for Namaste/salam/good morning", answer: "" }]
        ans.academicQA = [
            { question: "Points/shows body parts (head, nose, cycs, cars, hands, legs) when requested.", answer: "" },
            { question: "Names body parts when pointed to", answer: "" },
            { question: "Paints to 10 comman objects with which he has to interact in his/her home environment (eg.rice, dall, chapati, light, fan, mat, table, chair, shirt/frock, shorts/pants,etc.), when asked or when he wants", answer: "" },
            { question: "Says orally the names of the 10 common objects when shown when he wants.", answer: "" },
            { question: "Holds pencil and scribbles", answer: "" },
            { question: "Colours with a crayon within a given diagram", answer: "" },
            { question: "Traces on the given diagram", answer: "" },
            { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
            { question: "Copics a given figure/diagram", answer: "" },
            { question: "Groups common colours (red, green, blur, yellow) when given a group of coloured objects", answer: "" },
            { question: "Groups objects according to the size (big and small, long and short)", answer: "" },
            { question: "Gives objects/pictures of common colours when asked", answer: "" },
            { question: "Names common colours. (red, green, blue, yellow)", answer: "" },
            { question: "Points to the objects which are big and small/long and short upon request", answer: "" },
            { question: "Tells the size of the ohjeets (big & small, long & short)", answer: "" },
            { question: "Points to sets of objects to show more/less quantity", answer: "" },
            { question: "Tells which set has moreless quantity", answer: "" },
            { question: "Points to containers with either solids/liquids to show full and empty", answer: "" },
            { question: "Fells when a container is shown cither full or empty with or without liquid or solid", answer: "" },
            { question: "Rete counis upto 5", answer: "" },
            { question: "Counts and gives objects upto 5 when not asked sequentially", answer: "" },
            { question: "Counts and gives objects upto 10 when not asked sequentially.", answer: "" },
            { question: "Shows a numeral and places value when not asked sequentially", answer: "" },
            { question: "Names upto 5 numbers when not asked sequentially", answer: "" },
            { question: "Writes numerals upto 5 in a sequence", answer: "" },
            { question: "Writes numerals upto 5 when given dictation not sequentially", answer: "" },
            { question: "Points to alphabets (English/regional language) on a chart not asked sequentially (3 letter words in case of sight word icaching)", answer: "" },
            { question: "Names alphabets when asked not sequentially (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Writes alphabets when given dictation (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Identifies a clock or wrist watch", answer: "" },
            { question: "Tells points to when asked the use of clock or wrist watch", answer: "" },
            { question: "Differentiates money from other objects", answer: "" },
            { question: "Tells points to when asked the use of money", answer: "" },
            { question: "Groups Rs. 1, 2, 5 notes when given", answer: "" },
            { question: "Grck 1, 2, 5 rupee notes when asked", answer: "" },
            { question: "Points/tells when asked by showing Rs.1, 2, 5 notes", answer: "" },
            { question: "Counts and gives 1 rupee notes upto Rs.5 when asked", answer: "" },
            { question: "Points to atleast 5 pictures of animals when asked)", answer: "" },
            { question: "Names atleast 5 animals when shown pictures", answer: "" },
            { question: "Points to atleast 5 pictures of fruits when asked", answer: "" },
            { question: "Names atleast 5 fruits when shown pictures", answer: "" },
            { question: "Tells/points to the clothes (frock, shorts, shirt, T-shirt)he/she wears when asked", answer: "" },
            { question: "Uses words or gestures for 'now and later when necessary", answer: "" },
            { question: "Identifies/Names the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, acroplane, train)", answer: "" },]
        ans.occupationalQA = [
            { question: "Dusts with a duster the furniture in the classroom and home", answer: "" },
            { question: "Washes glasses and plates before and after meals.", answer: "" },
            { question: "Wipes glasses and plates with a cloth after washing", answer: "" },
            { question: "Folds small clothes (such as hand towel/panties).", answer: "" }]
        ans.recreationalQA = [{ question: "Watches T.V.Advertisements(indoor)", answer: "" },
        { question: "Dances/claps/taps with rhythm of music in Radio or T.V. (indoor)", answer: "" },
        { question: "Plays with block assembling and dismantling (indoor)", answer: "" },
        { question: "Colours with pencils or crayons (indoor)", answer: "" },
        { question: "Plays make believe games pretending to be teacher, mummy, daddy or elder sibling going to school/household keeping (indoor)", answer: "" },
        { question: "Arranges own things in their appropriate places, in a given room (indoor)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder (indoor)", answer: "" },
        { question: "Sees pictures in magazines without tearing the book (indoor)", answer: "" },//Sees pictures in magazines without tearing the book
        { question: "Plays with ball", answer: "" },
        { question: "Plays running and catching game/runs a race/duck walking/frog jumping, etc", answer: "" },
        { question: "Climbs jungle gym etc", answer: "" },
        { question: "Sand play", answer: "" },
        { question: "Water play", answer: "" },
        { question: "Plays hide and seek game/passing the parcel/musical chairs, etc", answer: "" },
        { question: "Plays on a slide", answer: "" },
        { question: "Swings on a swing", answer: "" }]
    }
    // console.log(ans)
    return ans
}

module.exports = findQAs